- name: Install classic snap pacakges for Ubuntu developement
  snap:
    name: "{{item}}"
    state: '{{ item.state | default("present") }}'
    classic: yes
  with_items:
    - git-ubuntu
    - multipass
    - snapcraft
    - ubuntu-make
    - flutter
    - ripgrep
    # - microk8s
    # - qabro

- name: install snap pacakges for ubuntu developement
  snap:
    name: "{{item}}"
    state: '{{ item.state | default("present") }}'
  with_items:
    - lxd
    - testflinger-cli
    - energy-tools
    - stress-ng

- name: install snap pacakges
  snap:
    name: ['bitwarden' , 'bw']
    state: '{{ item.state | default("present") }}'
