- name: install Visual Studio Code
  snap:
    name: "{{item}}"
    state: '{{ item.state | default("present") }}'
    classic: yes
  with_items:
    - code
- shell: |
    code --install-extension ms-azuretools.vscode-docker
    code --install-extension ms-vscode.cpptools
    code --install-extension dart-code.flutter
