- name: Install gnome-extensions-cli

  block:
    - apt:
        name: "{{item}}"
        state: '{{ item.state | default("present") }}'
      with_items:
        - gnome-shell-extensions
        - gnome-tweaks
        - chrome-gnome-shell
      become_user: root
  
  
    - name: Ensure pipx is installed
      package:
        name: pipx
        state: present
      become_user: root

    # Ensure pipx's path is set up
    - name: Ensure pipx path is added to shell
      shell: |
        python3 -m pipx ensurepath
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}"
      become: no

    # Install the desired software using pipx
    - name: Install gnome-extensions-cli with pipx
      shell: pipx install gnome-extensions-cli
      become: no

    - name: Clipboard Indicator by Tudmotu https://extensions.gnome.org/extension/779/clipboard-indicator/
      shell: id && echo $PATH && gext install clipboard-indicator@tudmotu.com
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

      become: no
        
    # - name: Install GSConnect by andyholmes https://extensions.gnome.org/extension/1319/gsconnect/
    #   shell: gext install gsconnect@andyholmes.github.io

    - name: Sound Input & Output Device Chooser by kgshank https://extensions.gnome.org/extension/906/sound-output-device-chooser/
      shell: gext install sound-output-device-chooser@kgshank.net
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
      become: no

    - name: Move applications to specific workspaces when they create windows. - https://extensions.gnome.org/extension/16/auto-move-windows/
      shell: gext install auto-move-windows@gnome-shell-extensions.gcampax.github.com
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
      become: no

    - name: Arrange workspaces in a two dimensional grid with workspace thumbnails. - https://extensions.gnome.org/extension/1485/workspace-matrix/
      shell: gext install wsmatrix@martin.zurowietz.de
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
      become: no

    - name: Arrange workspaces in a two dimensional grid with workspace thumbnails. - https://extensions.gnome.org/extension/1485/workspace-matrix/
      shell: gext install wsmatrix@martin.zurowietz.de
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
      become: no

    - name: Next Up, Show your next calendar event in the status bar - https://extensions.gnome.org/extension/5465/next-up/
      shell: gext install next-up@artisticat1.github.com
      environment:
        PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
      become: no
