- name: Install IMs
  snap:
    name: "{{item}}"
    state: '{{ item.state | default("present") }}'
  with_items:
    - telegram-desktop
    - mattermost-desktop
    - zoom-client
    - electronic-wechat

- name: Install IM clients with classic snaps
  snap:
    name: "{{item}}"
    state: '{{ item.state | default("present") }}'
  with_items:
    - skype
    - slack
