
- name: Setup for personal settings.
  block:
  - name: Change default shell to zsh
    shell: chsh -s $(which zsh) "{{ansible_ssh_user}}"
    become: yes
    become_user: root

  - name: ohmyzsh zsh configuration
    git:
      repo: 'https://github.com/chihchun/oh-my-zsh.git'
      dest: "{{ansible_env.HOME}}/.oh-my-zsh"
      version: chihchun

  - name: copy personal data
    import_tasks: stuff.yaml

  - name: Setup fcitx
    command: "im-config -n fcitx"
