
- name: Setup for personal settings.
  block:

  - name: install zsh
    import_tasks: zsh.yaml
    become: yes
    become_user: root

  - name: copy personal data
    import_tasks: stuff.yaml

  - name: setup locale for Chinese
    import_tasks: locale.yaml
    become: yes
    become_user: root

  - name: GNOME tweaks
    import_tasks: gnome-tweak.yaml

  - name: install utils.
    apt:
      name: "{{item}}"
      state: '{{ item.state | default("present") }}'
    with_items:
      #      - mlocate
      - pwgen
    become: yes
    become_user: root
