- name: Synchronize stuff
  synchronize:
      src: "{{lookup('env','HOME')}}/stuff"
      dest: "/home/{{ansible_ssh_user}}"

- name: Synchronize Projects
  synchronize:
      src: "{{lookup('env','HOME')}}/Projects"
      dest: "/home/{{ansible_ssh_user}}"

- name: Create symbolic link to bin
  file:
    src: "/home/{{ansible_ssh_user}}/stuff/bin"
    dest: "/home/{{ansible_ssh_user}}/bin"
    state: link

- name: setup configurations
  shell: "/home/{{ansible_ssh_user}}/stuff/etc/setuppath.sh"
