
- name: Install packages
  block:
  - name: install dev packages
    apt:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
      purge: yes

    with_items:
      - name: devscripts

  - name: install desktop packages
    apt:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
      purge: yes

    with_items:
      - name: terminator

  - name: install Chinese language packages
    apt:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
      purge: yes

    with_items:
      - name: language-pack-gnome-zh-hant
      - name: fcitx
      - name: fcitx-chewing

  - name: install sync tools
    apt:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
      purge: yes

    with_items:
      - name: unison
      - name: rsync

  become: yes
  become_user: root

- name: Setup fcitx
  command: "im-config -n fcitx"

- name: Change default shell to zsh
  shell: chsh -s $(which zsh) "{{ansible_ssh_user}}"
  become: yes
  become_user: root

- name: ohmyzsh zsh configuration
  git:
    repo: 'https://github.com/chihchun/oh-my-zsh.git'
    dest: "{{ansible_env.HOME}}/.oh-my-zsh"
    version: chihchun
