- name: Find apt source from /etc/apt/sources.list.d/
  find:
    paths: /etc/apt
    patterns: '*.list'
  register: aptsources

- debug:
    var: aptsources
    verbosity: 2

- name: disable all apt src
  replace: 
    dest: '{{item.path}}'
    regexp: "^(deb-src .*?)$"
    replace: '# \1'
  with_items: '{{aptsources.files}}'
  become: yes
  become_user: root