- name: Install packages which I can not live without
  block:
  - name: upgrade packages
    apt:
      upgrade: dist
      update_cache: yes

  - name: install base packages
    apt:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
      purge: yes

    with_items:
      - name: htop
      - name: tmux
      - name: zsh
      - name: vim

  become: yes
  become_user: root